Repository DigitalKin-ai/service-apis-py, pull requests merged in 2025-03, with the labels that each got.

#13 Upgrade and clean github action & bump package to 0.0.3
  .bumpversion.cfg
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  src/digitalkin_proto/__init__.py
  taskfile.yml
  uv.lock
Labels: 🐛 bug, 🚠 infrastructure

#15 v0.0.3
  .bumpversion.cfg
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  src/digitalkin_proto/__init__.py
  taskfile.yml
  uv.lock
Labels: 🎛️ dependencies, 🐛 bug, 📚 doc

#19 Remove pypi token to use OICD trusted publisher, bump versions of actions and add github token
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: 🐛 bug, 🚀 ok for Reviews, 🚠 infrastructure

#20 Fix ci
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: 🐛 bug, 🚀 ok for Reviews

#24 v0.0.7
  .bumpversion.cfg
  .github/workflows/publish.yml
  pyproject.toml
  src/digitalkin_proto/__init__.py
Labels: 🐛 bug, 🚀 ok for Reviews

#25 feat(services): adding cost, filesystem and storage services
  taskfile.yml
  uv.lock
Labels: 💓 enhancement, 🚀 ok for Reviews
